name: Toggle README title

# Execute manualmente ou por cron (a cada hora)
on:
  workflow_dispatch: {}
  schedule:
    # '0 * * * *' = a cada hora. Ajuste se quiser.
    - cron: '0 * * * *'

permissions:
  contents: write  # permite o workflow escrever no repositório

jobs:
  toggle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Toggle title in README
        env:
          T1: "👋 Hello, I’m Guilherme Pinheiro!"
          T2: "💻 I’m a Full Stack Developer!"
          README_FILE: "README.md"
        run: |
          python3 - <<'PY'
          import re, os, sys
          T1 = os.environ['T1']
          T2 = os.environ['T2']
          README = os.environ['README_FILE']
          start = "<!-- TITLE_START -->"
          end = "<!-- TITLE_END -->"

          with open(README, "r", encoding="utf-8") as f:
              text = f.read()

          pattern = re.compile(re.escape(start) + r"(.*?)" + re.escape(end), re.S)
          m = pattern.search(text)
          if not m:
              print("ERROR: marcadores TITLE_START / TITLE_END não encontrados em", README)
              sys.exit(1)

          inner = m.group(1).strip()
          # Decide qual título colocar
          if T1 in inner:
              new_inner = T2
          else:
              new_inner = T1

          replacement = start + "\n" + new_inner + "\n" + end
          new_text = pattern.sub(replacement, text, count=1)

          if new_text == text:
              print("No change needed.")
              sys.exit(0)

          with open(README, "w", encoding="utf-8") as f:
              f.write(new_text)

          print("Updated README title to:", new_inner)
          PY

      - name: Commit changed README
        run: |
          git add README.md || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "ci: toggle README title"
            git push
          fi
